
package br.com.uninorte.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControleUsuarioService", targetNamespace = "http://uninorte.com.br/", wsdlLocation = "http://localhost:10010/controleUsuario?wsdl")
public class ControleUsuarioService
    extends Service
{

    private final static URL CONTROLEUSUARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLEUSUARIOSERVICE_EXCEPTION;
    private final static QName CONTROLEUSUARIOSERVICE_QNAME = new QName("http://uninorte.com.br/", "ControleUsuarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10010/controleUsuario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLEUSUARIOSERVICE_WSDL_LOCATION = url;
        CONTROLEUSUARIOSERVICE_EXCEPTION = e;
    }

    public ControleUsuarioService() {
        super(__getWsdlLocation(), CONTROLEUSUARIOSERVICE_QNAME);
    }

    public ControleUsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLEUSUARIOSERVICE_QNAME, features);
    }

    public ControleUsuarioService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLEUSUARIOSERVICE_QNAME);
    }

    public ControleUsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLEUSUARIOSERVICE_QNAME, features);
    }

    public ControleUsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControleUsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControleUsuario
     */
    @WebEndpoint(name = "ControleUsuarioPort")
    public ControleUsuario getControleUsuarioPort() {
        return super.getPort(new QName("http://uninorte.com.br/", "ControleUsuarioPort"), ControleUsuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControleUsuario
     */
    @WebEndpoint(name = "ControleUsuarioPort")
    public ControleUsuario getControleUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uninorte.com.br/", "ControleUsuarioPort"), ControleUsuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLEUSUARIOSERVICE_EXCEPTION!= null) {
            throw CONTROLEUSUARIOSERVICE_EXCEPTION;
        }
        return CONTROLEUSUARIOSERVICE_WSDL_LOCATION;
    }

}
