
package br.com.uninorte.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControleUsuario", targetNamespace = "http://uninorte.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControleUsuario {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "listarperfilcontrole", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.Listarperfilcontrole")
    @ResponseWrapper(localName = "listarperfilcontroleResponse", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.ListarperfilcontroleResponse")
    @Action(input = "http://uninorte.com.br/ControleUsuario/listarperfilcontroleRequest", output = "http://uninorte.com.br/ControleUsuario/listarperfilcontroleResponse")
    public void listarperfilcontrole();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "conectarcontrole", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.Conectarcontrole")
    @ResponseWrapper(localName = "conectarcontroleResponse", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.ConectarcontroleResponse")
    @Action(input = "http://uninorte.com.br/ControleUsuario/conectarcontroleRequest", output = "http://uninorte.com.br/ControleUsuario/conectarcontroleResponse")
    public void conectarcontrole();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "estaConectadocontrole", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.EstaConectadocontrole")
    @ResponseWrapper(localName = "estaConectadocontroleResponse", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.EstaConectadocontroleResponse")
    @Action(input = "http://uninorte.com.br/ControleUsuario/estaConectadocontroleRequest", output = "http://uninorte.com.br/ControleUsuario/estaConectadocontroleResponse")
    public boolean estaConectadocontrole();

    /**
     * 
     * @param inserirusuario
     */
    @WebMethod
    @RequestWrapper(localName = "inserirusuariocontrole", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.Inserirusuariocontrole")
    @ResponseWrapper(localName = "inserirusuariocontroleResponse", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.InserirusuariocontroleResponse")
    @Action(input = "http://uninorte.com.br/ControleUsuario/inserirusuariocontroleRequest", output = "http://uninorte.com.br/ControleUsuario/inserirusuariocontroleResponse")
    public void inserirusuariocontrole(
        @WebParam(name = "inserirusuario", targetNamespace = "")
        Usuario inserirusuario);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "desconectarcontrole", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.Desconectarcontrole")
    @ResponseWrapper(localName = "desconectarcontroleResponse", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.DesconectarcontroleResponse")
    @Action(input = "http://uninorte.com.br/ControleUsuario/desconectarcontroleRequest", output = "http://uninorte.com.br/ControleUsuario/desconectarcontroleResponse")
    public void desconectarcontrole();

    /**
     * 
     * @param apagarUsuarioCPF
     */
    @WebMethod
    @RequestWrapper(localName = "apagarusuariocontrole", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.Apagarusuariocontrole")
    @ResponseWrapper(localName = "apagarusuariocontroleResponse", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.ApagarusuariocontroleResponse")
    @Action(input = "http://uninorte.com.br/ControleUsuario/apagarusuariocontroleRequest", output = "http://uninorte.com.br/ControleUsuario/apagarusuariocontroleResponse")
    public void apagarusuariocontrole(
        @WebParam(name = "apagarUsuarioCPF", targetNamespace = "")
        String apagarUsuarioCPF);

    /**
     * 
     * @param editarusuarioTelefone
     * @param editarusuarioEmail
     * @param editarusuarioMunicipio
     * @param editarusuarioCPF
     * @param editarusuarioPerfil
     * @param editarusuarioFuncao
     * @param editarusuarioNome
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editarusuariocontrole", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.Editarusuariocontrole")
    @ResponseWrapper(localName = "editarusuariocontroleResponse", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.EditarusuariocontroleResponse")
    @Action(input = "http://uninorte.com.br/ControleUsuario/editarusuariocontroleRequest", output = "http://uninorte.com.br/ControleUsuario/editarusuariocontroleResponse")
    public String editarusuariocontrole(
        @WebParam(name = "editarusuarioNome", targetNamespace = "")
        String editarusuarioNome,
        @WebParam(name = "editarusuarioCPF", targetNamespace = "")
        String editarusuarioCPF,
        @WebParam(name = "editarusuarioTelefone", targetNamespace = "")
        String editarusuarioTelefone,
        @WebParam(name = "editarusuarioEmail", targetNamespace = "")
        String editarusuarioEmail,
        @WebParam(name = "editarusuarioFuncao", targetNamespace = "")
        String editarusuarioFuncao,
        @WebParam(name = "editarusuarioMunicipio", targetNamespace = "")
        String editarusuarioMunicipio,
        @WebParam(name = "editarusuarioPerfil", targetNamespace = "")
        String editarusuarioPerfil);

    /**
     * 
     * @param buscarUsuarioCPF
     * @param buscarUsuarioUsuario
     */
    @WebMethod
    @RequestWrapper(localName = "buscarUsuario", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.BuscarUsuario")
    @ResponseWrapper(localName = "buscarUsuarioResponse", targetNamespace = "http://uninorte.com.br/", className = "br.com.uninorte.cliente.BuscarUsuarioResponse")
    @Action(input = "http://uninorte.com.br/ControleUsuario/buscarUsuarioRequest", output = "http://uninorte.com.br/ControleUsuario/buscarUsuarioResponse")
    public void buscarUsuario(
        @WebParam(name = "buscarUsuarioCPF", targetNamespace = "")
        String buscarUsuarioCPF,
        @WebParam(name = "buscarUsuarioUsuario", targetNamespace = "")
        Usuario buscarUsuarioUsuario);

}
